### ISSUE TITLE
Can't register on XBSLink website

### ISSUE THREAD

**Issue by TwitchBronBron** [seuffert/XBSlink#16]
Sorry for leaving this comment here, but I was unable to leave new messages on the website because the captcha is not working.

There seems to be an issue with the CAPTCHA when trying to register (http://www.seuffert.biz/xbslink/wp-login.php?action=register) and also when trying to contact you through the contact page (http://www.seuffert.biz/xbslink/contact). It gives this error: ERROR: Unreadable CAPTCHA token file.

**Comment by seuffert** [comment]
user registration is disabled for the time being
