### ISSUE TITLE
Can somebody compile or provide compile instructions?

### ISSUE THREAD

**Issue by JoneKone** [seuffert/XBSlink#18]
Hi. and yes sorry..

I can't find the released compiled version of this anywhere anymore, and i have no idea/knowhow to compile this... Although it seems to be an abandoned project, raven had a commit to update it 2017... Sooo, if anybody would like to compile this? =) I would like him/her

**Comment by JoneKone** [comment]
Nevermind Found one https://github.com/Ch0wW/XBSlink/commit/443ef59480a0d4a4f08b18df71b0f9238afa0807

**Comment by barronwaffles** [comment]
The official builds are available here - https://www.seuffert.biz/xbslink/xbslink-download

You should be able to generate a binary without any additional configuration inside Visual Studio - just open the solution and select the desired target.

**Comment by seuffert** [comment]
i just realized that the wordpress download plugin doesn't work anymore. will fix soon

**Comment by seuffert** [comment]
downloads are available again.
